# This is a basic workflow to help you get started with Actions

name: Build and Deploy (CI/CD)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted-windows
    steps:
      - uses: actions/checkout@v2

      - uses: mymindstorm/setup-emsdk@v11
        with:
          emsdk_version: 3.1.10
          emsdk_path: emsdk-cache

      - run: ./bin/build.sh