# This is a basic workflow to help you get started with Actions

name: Build and Deploy (CI/CD)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: self-hosted-windows
    env:
      s3-bucket: 'keeper.ziru.link'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Install Dependencies
        run: ./bin/setup.sh

      - name: EMCC Build
        run: ./bin/build.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:             us-west-1
      
      - name: Deploy to S3
        run: aws s3 sync ./dist/ s3://${{ env.s3-bucket }} --delete

      - name: Deploy to CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*' 